export const NAME = "NAME";
export const MESSAGES = "MESSAGES";
export const ALLUSERS = "ALLUSERS";
export const TOGGLECHATNAME = "TOGGLECHATNAME";
export const NOTIFICATION = "NOTIFICATION";
export const NOTIFICATIONPERMISSION = "NOTIFICATIONPERMISSION";
